language: groovy

jdk:
    - oraclejdk7

branches:
    only:
        - master

before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

script: ./grailsw refresh-dependencies
    && ./grailsw test-app
