language: groovy

addons:
    sauce_connect:
        username: "masood09"
        access_key: "a677f19e-8103-4576-8ab8-71c0dbfe29c2"

jdk:
    - oraclejdk7
    # - openjdk7
    # - openjdk6

branches:
    only:
        - master

before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

script: ./grailsw refresh-dependencies
    && ./grailsw -Dgeb.env=traviswin7ie9 test-app
    && ./grailsw -Dgeb.env=traviswin7ie10 test-app
    && ./grailsw -Dgeb.env=traviswin8ie10 test-app
    && ./grailsw -Dgeb.env=traviswin81ie11 test-app
